#!/bin/sh

###for my Arch-linux
#this script must running under internet and root
-----------------------------------------------
#for kepade#gmx-x
-----------------------------------------------


if [ $(id -u) != "0" ]; then
    echo "Error: You must be root to run this script, please use root "
    exit 1
    else
       rewrite
fi
###START

rewrite(){
loadkeys us
ping -c 4 baidu.com
reflector --latest 200 --protocol https --sort rate --save /etc/pacman.d/mirrorlisttimedatectl set-ntp true
fdisk -l
cfdisk ##delete sda6 and rewrite
mkfs.ext4 /dev/sda6
mount /dev/sda6 /mnt
mkdir /mnt/boot
nano /etc/pacman.d/mirrorlist ##ctrl+K
pacman -Syy
pacman -S archlinux-keyring
pacstrap -i /mnt base base-devel
genfstab -U /mnt >> /mnt/etc/fstab
arch-chroot /mnt

ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
hwclock --systohc --utc
nano /etc/locale.gen
locale-gen
echo LANG=en_US.UTF-8 >/etc/locale.conf
echo kepade16 >/etc/hostname
passwd
systemctl enable dhcpcd.service
pacman -S 'xorg' 'gnome' xorg-xinit iw wpa_supplicant dialog grub os-prober efibootmgr
systemctl enable gdm
systemctl enable NetworkManager.service

useradd -m -g users -G wheel -s /bin/bash gmx-x
passwd gmx-x
chmod u+w /etc/sudoers
echo gmx-x ALL=(ALL)ALL >>/etc/sudoers

grub-install --recheck /dev/sda
grub-mkconfig -o /boot/grub/grub.cfg

pacman -S   ntp  alsa-utils  net-tools htop  vsftpd openssh intel-ucode
reboot


################################################################################################

echo '[multilib]
Include = /etc/pacman.d/mirrorlist

[archlinuxcn]
SigLevel = Optional TrustedOnly
Server = https://mirrors.ustc.edu.cn/archlinuxcn/$arch
#不安装（存在代理问题）
[blackarch]
SigLevel = Optional TrustAll
Server = https://mirrors.ustc.edu.cn/blackarch/$repo/os/$arch
' >>/etc/pacman.conf
pacman -Syy
pacman -S archlinuxcn-keyring
pacman -S blackarch-keyring
pacman -Syy
pacman -S  ufw wqy-zenhei  wget yay file-roller unrar p7zip alacarte pacaur  hostapd dnsmasq  brasero cmus    lolcat aria2 git vim   virtualbox zsh oh-my-zsh-git xfce4-terminal tor neofetch screenfetch  tmux  macchanger vlc gnome-tweak-tool  gedit python-pyopenssl python2-pyopenssl libffi pygtk python2-notify nss  dconf-editor ntfs-3g dosfstools gnome-shell-extension-dash-to-dock-git  gnome-shell-extension-easyscreencast strace bind-tools    gnome-shell-extension-simple-net-speed-git  gnome-shell-extension-topicons-plus-git reflector rsync wipe adobe-source-code-pro-fonts gnome-shell-extension-coverflow-alt-tab-git shadowsocks-libev simple-obfs


software
#create swap
cd \
mkdir swap
cd swap
dd if=/dev/zero of=swap bs=1024 count="4000000"
mkswap -f  swap﻿
echo /swap/swap none swap defaults 0 0 >>/etc/fstab

cp /usr/share/oh-my-zsh/zshrc  ~/.zshrc
pacman -S fcitx-googlepinyin fcitx-im fcitx-configtool
cp -rf environment /etc
cp -rf group /etc
cp -rf group- /etc
grub-mkconfig -o /boot/grub/grub.cfg
sudo systemctl start ufw
sudo systemctl enable ufw
##can choice
#lib32
pacman -S  atom  proxychains  netease-cloud-music visual-studio-code  rkhunter nmap hping telegram-desktop wine  lib32-freetype2 lib32-libxinerama lib32-libxcursor lib32-libxrandr lib32-libxrender lib32-libxi lib32-libxext  lib32-libxfixes lib32-libsm lib32-fontconfig lib32-libpng   lib32-libgpg-error   lib32-libgcrypt  lib32-xz  lib32-attr   lib32-libcap  lib32-systemd   lib32-dbus  lib32-pcre   lib32-util-linux  lib32-glib2 lib32-harfbuzz
grub-mkconfig -o /boot/grub/grub.cfg

#######this step is to install some software and also will take some time
echo 'https://forum.manjaro.org/t/install-apache-mariadb-php-lamp-2016/1243/8'
cd /srv
ls
cd
cp -rf http/ /srv/

cp -rf sshd_config /etc/ssh/sshd_config
cp -rf vsftpd.conf /etc/vsftpd.conf
cd

##start this without root but sudo
cp html/  /home/gmx-x/
cd gnome
chmod +x gnomeinstall.sh
./gnomeinstall.sh
echo 'use "dash to dock" to change icon local'
reflector --latest 200 --protocol https --sort rate --save /etc/pacman.d/mirrorlist

pacman -Syyu
#无用了
echo '配置xx-net( kepade-149711|ringed-hallway-149711|poetic-bison-168205|rapid-pottery-168205 ) ,设置代理为[http://127.0.0.1:8086/proxy.pac] kepade12@gmail.com'
echo '配置github(kepade12@gmail.com)  ftp&&ssh 的用户和读写权限 '
}



#end
