#!/bin/sh

## change mac address rand()

sudo ifconfig enp1s0 down
sudo macchanger -r enp1s0
sudo ifconfig enp1s0 up
sudo ifconfig wlp2s0 down
sudo macchanger -r wlp2s0
sudo ifconfig wlp2s0 up

#connect socks5
#nohup ss-local -s 45.76.79.82 -p 8388  -l 1080 -k mame -m aes-256-cfb &                          #已死
#cd &&cd ftp/shell/shadowsocksr/shadowsocks && nohup  python local.py -s 185.14.30.138 -p 443  -k 15psocksconnect -m none -O auth_chain_a -o tls1.2_ticket_fastauth --fast-open &
#cd &&cd ftp/shell/shadowsocksr/shadowsocks && nohup  python local.py -s 5.45.121.21 -p 443 -k 15psocksconnect -m none -O auth_chain_a -o tls1.2_ticket_fastauth --fast-open &
#cd &&cd ftp/shell/shadowsocksr/shadowsocks && nohup  python local.py -s 45.77.5.51 -p  8080 -k  mamee>>Y1  -m none -O  auth_chain_b  -o tls1.2_ticket_fastauth --fast-open &
cd && cd /home/gmx-x/ftp/html && nohup ss-local -c ss.json &
#cd && cd /home/gmx-x/ftp/html && nohup ss-local -c ss2.json &


#打开浏览器
#cd ftp/html/ && nohup '/home/gmx-x/下载/firefox/firefox' & 

#开个人热点
# nohup sudo create_ap wlp2s0 lo kepade qq23qwert &


#连接校园网并杀死认证进程 
cd /home/gmx-x/ftp/html/DrClient/  && nohup '/home/gmx-x/ftp/html/DrClient/DrClientLinux' &
sleep 20
killall /home/gmx-x/ftp/html/DrClient/DrClientLinux


#iptables -F 
#会清空现有的iptables规则，如果您是企业用户或是已在运行的服务器，需要自己检查现有iptables规则，并手动合并规则，否则可能会造成很严重的网络问题。
#iptables -A INPUT -p tcp --dport 23322 -j ACCEPT等就没什么解释的了，如果您对外开放这些服务，就向公众开放这些端口。没有开放的端口，就会匹配到最后的 DROP 规则。
#iptables -I INPUT -s 61.148.52.162 -j ACCEPT，IP 白名单。如果您的管理环境拥有固定IP，比如您的公司使用固定IP上网，则可以使用这个方法放行。这是一条非必需的规则。
#iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT，接受已建立连接的所有请求。这其实是一条防手残规则，防止在你执行这些脚本时把你的 SSH 连接断掉。
#iptables -A INPUT -p icmp -m icmp --icmp-type 8 -j ACCEPT，允许 PING。这是一条非必需的规则。如果您不想让自己的服务器更隐秘，则可以把 ACCEPT 替换成 DROP，但这样出现未知网络问题时，您也将 ping 不通自己的服务器，无法确认到底是谁哪里的网络问题了。（白名单不受限）
#iptables -A OUTPUT -j ACCEPT，接受本机向外发出的请求，不解释。除非你服务器要玩单机。
#iptables -A INPUT -p tcp --dport 3128 -j DROP，DROP 掉发入3128端口的tcp请求。3128端口是 squid 的默认端口，关于 squid 
#是什么您可以自行谷歌。额外添加此条规则可以帮助您查看有多少混蛋在扫你的这个端口。这是一条非必需的规则。
#iptables -I INPUT -s 104.194.76.27 -j DROP，IP 黑名单。这个IP是混蛋，我完全不想让这个用户访问我的任何服务（包括正常对外开放的端口、ping）
#iptables -A INPUT -j DROP，所有发入未开放端口的流量一律 drop。
